# Auto-generated by sprite animation tool
ANIMATION = 'jump'
SHEET = '../../../../Assests/Sword Master Sprite Sheet 90x37.png'
FRAME_SIZE = (90, 37)
MARGIN = 0
SPACING = 0
FRAMES = [
    {'x': 0, 'y': 481, 'w': 90, 'h': 37, 'row': 13, 'col': 0, 'trimmed': {'x': 22, 'y': 490, 'w': 12, 'h': 23}, 'offset': {'x': 22, 'y': 9}, 'pivot': {'x': 6, 'y': 22}},
    {'x': 90, 'y': 481, 'w': 90, 'h': 37, 'row': 13, 'col': 1, 'trimmed': {'x': 112, 'y': 490, 'w': 12, 'h': 23}, 'offset': {'x': 22, 'y': 9}, 'pivot': {'x': 6, 'y': 22}},
    {'x': 180, 'y': 481, 'w': 90, 'h': 37, 'row': 13, 'col': 2, 'trimmed': {'x': 202, 'y': 490, 'w': 12, 'h': 23}, 'offset': {'x': 22, 'y': 9}, 'pivot': {'x': 6, 'y': 22}},
]
TRIMMED = [
    (22, 490, 12, 23, 22, 9),
    (112, 490, 12, 23, 22, 9),
    (202, 490, 12, 23, 22, 9),
]
PIVOTS = [
    (6, 22),
    (6, 22),
    (6, 22),
]
